# Generated by Django 3.2 on 2021-05-17 13:53

from django.db import migrations, models
import myproject.myapp.base.BaseModel
import myproject.myapp.features.Analytics.protocol.AnalyticProtocol


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_analyticmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamingModel',
            fields=[
                ('game_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('game_title', models.CharField(max_length=6000)),
                ('game_win_rate', models.FloatField(verbose_name='Success Rate')),
            ],
            bases=(models.Model, myproject.myapp.features.Analytics.protocol.AnalyticProtocol.AnalyticProtocol, myproject.myapp.base.BaseModel.BaseModelProtocol),
        ),
    ]
