# Generated by Django 3.2 on 2021-05-17 14:44

from django.db import migrations, models
import django.db.models.deletion
import myproject.myapp.base.BaseModel
import myproject.myapp.features.Analytics.protocol.AnalyticProtocol


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_gamingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchModel',
            fields=[
                ('match_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('champ_type', models.CharField(default='Default_Champ', max_length=100)),
                ('match_win_rate', models.FloatField(default=0.0, verbose_name='Match-Win-Rate')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.gamingmodel')),
            ],
            bases=(models.Model, myproject.myapp.features.Analytics.protocol.AnalyticProtocol.AnalyticProtocol, myproject.myapp.base.BaseModel.BaseModelProtocol),
        ),
    ]
